### ISSUE TITLE
Build broken on Linux

### ISSUE THREAD

**Issue by ebachard** [edselmalasig/sndpeek-imgui#1]
Hi,

Thanks for your nice program. I tried to build it on Linux (alsa version) , and the build was slightly broken.
- missing files to be built (imgui*.cpp not in the makefile.alsa)
- missing includes
- missing flags for the linking
- wrong SDL version ? (looks like imgui uses SDL2 while sndpeek-imgui uses SDL(1.2 ???)
- wrong OpenGL context (maybe my fault)

Where can we find the sound-track ? Looks very nice :-)

FYI, and if ever this can help, you'll find below a diff showing several "improvement" (maybe some are plain wrong, apologies in advance)

Current state : the build is ok, but the window is Frozen (maybe my fault, perhaps I should use OpenGL 2 only => will try to debug soon)
`diff --git a/src/marsyas/LPC.h b/src/marsyas/LPC.h
index 8f774f1..bce6543 100755
--- a/src/marsyas/LPC.h
+++ b/src/marsyas/LPC.h
@@ -39,6 +39,10 @@ in Speech Recognition research.
 #include "AutoCorrelation.h"
 #include "MarSignal.h"
 
+/* abs not declared in this scope */
+#include <stdlib.h>
+
+
 class LPC: public System
 {
 private:
diff --git a/src/sndpeek-bin/AutoCorrelation.o b/src/sndpeek-bin/AutoCorrelation.o
deleted file mode 100644
index ac4222d..0000000
Binary files a/src/sndpeek-bin/AutoCorrelation.o and /dev/null differ
diff --git a/src/sndpeek-bin/Centroid.o b/src/sndpeek-bin/Centroid.o
deleted file mode 100644
index 048c36b..0000000
Binary files a/src/sndpeek-bin/Centroid.o and /dev/null differ
diff --git a/src/sndpeek-bin/Communicator.o b/src/sndpeek-bin/Communicator.o
deleted file mode 100644
index 1e787bb..0000000
Binary files a/src/sndpeek-bin/Communicator.o and /dev/null differ
diff --git a/src/sndpeek-bin/DownSampler.o b/src/sndpeek-bin/DownSampler.o
deleted file mode 100644
index 05360a4..0000000
Binary files a/src/sndpeek-bin/DownSampler.o and /dev/null differ
diff --git a/src/sndpeek-bin/Flux.o b/src/sndpeek-bin/Flux.o
deleted file mode 100644
index a9a09a2..0000000
Binary files a/src/sndpeek-bin/Flux.o and /dev/null differ
diff --git a/src/sndpeek-bin/Hamming.o b/src/sndpeek-bin/Hamming.o
deleted file mode 100644
index 63c3725..0000000
Binary files a/src/sndpeek-bin/Hamming.o and /dev/null differ
diff --git a/src/sndpeek-bin/LPC.o b/src/sndpeek-bin/LPC.o
deleted file mode 100644
index 9057369..0000000
Binary files a/src/sndpeek-bin/LPC.o and /dev/null differ
diff --git a/src/sndpeek-bin/MFCC.o b/src/sndpeek-bin/MFCC.o
deleted file mode 100644
index 461df6e..0000000
Binary files a/src/sndpeek-bin/MFCC.o and /dev/null differ
diff --git a/src/sndpeek-bin/MagFFT.o b/src/sndpeek-bin/MagFFT.o
deleted file mode 100644
index 1c8eb34..0000000
Binary files a/src/sndpeek-bin/MagFFT.o and /dev/null differ
diff --git a/src/sndpeek-bin/MarSignal.o b/src/sndpeek-bin/MarSignal.o
deleted file mode 100644
index 48cf181..0000000
Binary files a/src/sndpeek-bin/MarSignal.o and /dev/null differ
diff --git a/src/sndpeek-bin/NormRMS.o b/src/sndpeek-bin/NormRMS.o
deleted file mode 100644
index 2766ab3..0000000
Binary files a/src/sndpeek-bin/NormRMS.o and /dev/null differ
diff --git a/src/sndpeek-bin/RMS.o b/src/sndpeek-bin/RMS.o
deleted file mode 100644
index eca4398..0000000
Binary files a/src/sndpeek-bin/RMS.o and /dev/null differ
diff --git a/src/sndpeek-bin/Rolloff.o b/src/sndpeek-bin/Rolloff.o
deleted file mode 100644
index 3b291a2..0000000
Binary files a/src/sndpeek-bin/Rolloff.o and /dev/null differ
diff --git a/src/sndpeek-bin/RtAudio.o b/src/sndpeek-bin/RtAudio.o
deleted file mode 100644
index d06ce79..0000000
Binary files a/src/sndpeek-bin/RtAudio.o and /dev/null differ
diff --git a/src/sndpeek-bin/Stk.o b/src/sndpeek-bin/Stk.o
deleted file mode 100644
index aa9287d..0000000
Binary files a/src/sndpeek-bin/Stk.o and /dev/null differ
diff --git a/src/sndpeek-bin/System.o b/src/sndpeek-bin/System.o
deleted file mode 100644
index b1626f0..0000000
Binary files a/src/sndpeek-bin/System.o and /dev/null differ
diff --git a/src/sndpeek-bin/Thread.o b/src/sndpeek-bin/Thread.o
deleted file mode 100644
index 4a014d7..0000000
Binary files a/src/sndpeek-bin/Thread.o and /dev/null differ
diff --git a/src/sndpeek-bin/chuck_fft.o b/src/sndpeek-bin/chuck_fft.o
deleted file mode 100644
index e50c28e..0000000
Binary files a/src/sndpeek-bin/chuck_fft.o and /dev/null differ
diff --git a/src/sndpeek-bin/fmatrix.o b/src/sndpeek-bin/fmatrix.o
deleted file mode 100644
index a8ab3a5..0000000
Binary files a/src/sndpeek-bin/fmatrix.o and /dev/null differ
diff --git a/src/sndpeek-bin/fvec.o b/src/sndpeek-bin/fvec.o
deleted file mode 100644
index 730fb33..0000000
Binary files a/src/sndpeek-bin/fvec.o and /dev/null differ
diff --git a/src/sndpeek-bin/sndpeek b/src/sndpeek-bin/sndpeek
deleted file mode 100755
index 3e4b949..0000000
Binary files a/src/sndpeek-bin/sndpeek and /dev/null differ
diff --git a/src/sndpeek-bin/sndpeek.o b/src/sndpeek-bin/sndpeek.o
deleted file mode 100644
index f598cd8..0000000
Binary files a/src/sndpeek-bin/sndpeek.o and /dev/null differ
diff --git a/src/sndpeek-bin/util_sndfile.o b/src/sndpeek-bin/util_sndfile.o
deleted file mode 100644
index c17f053..0000000
Binary files a/src/sndpeek-bin/util_sndfile.o and /dev/null differ
diff --git a/src/sndpeek/AutoCorrelation.o b/src/sndpeek/AutoCorrelation.o
deleted file mode 100644
index 5f43edf..0000000
Binary files a/src/sndpeek/AutoCorrelation.o and /dev/null differ
diff --git a/src/sndpeek/Centroid.o b/src/sndpeek/Centroid.o
deleted file mode 100644
index 4c1a989..0000000
Binary files a/src/sndpeek/Centroid.o and /dev/null differ
diff --git a/src/sndpeek/Communicator.o b/src/sndpeek/Communicator.o
deleted file mode 100644
index 27d249e..0000000
Binary files a/src/sndpeek/Communicator.o and /dev/null differ
diff --git a/src/sndpeek/DownSampler.o b/src/sndpeek/DownSampler.o
deleted file mode 100644
index 7f1e073..0000000
Binary files a/src/sndpeek/DownSampler.o and /dev/null differ
diff --git a/src/sndpeek/Flux.o b/src/sndpeek/Flux.o
deleted file mode 100644
index 3db60a5..0000000
Binary files a/src/sndpeek/Flux.o and /dev/null differ
diff --git a/src/sndpeek/Hamming.o b/src/sndpeek/Hamming.o
deleted file mode 100644
index 76186be..0000000
Binary files a/src/sndpeek/Hamming.o and /dev/null differ
diff --git a/src/sndpeek/LPC.o b/src/sndpeek/LPC.o
deleted file mode 100644
index c1add97..0000000
Binary files a/src/sndpeek/LPC.o and /dev/null differ
diff --git a/src/sndpeek/MFCC.o b/src/sndpeek/MFCC.o
deleted file mode 100644
index 45d7155..0000000
Binary files a/src/sndpeek/MFCC.o and /dev/null differ
diff --git a/src/sndpeek/MagFFT.o b/src/sndpeek/MagFFT.o
deleted file mode 100644
index 99d1a6f..0000000
Binary files a/src/sndpeek/MagFFT.o and /dev/null differ
diff --git a/src/sndpeek/MarSignal.o b/src/sndpeek/MarSignal.o
deleted file mode 100644
index 326f6ed..0000000
Binary files a/src/sndpeek/MarSignal.o and /dev/null differ
diff --git a/src/sndpeek/NormRMS.o b/src/sndpeek/NormRMS.o
deleted file mode 100644
index dfb5f1f..0000000
Binary files a/src/sndpeek/NormRMS.o and /dev/null differ
diff --git a/src/sndpeek/RMS.o b/src/sndpeek/RMS.o
deleted file mode 100644
index 83b4daa..0000000
Binary files a/src/sndpeek/RMS.o and /dev/null differ
diff --git a/src/sndpeek/Rolloff.o b/src/sndpeek/Rolloff.o
deleted file mode 100644
index 18bcd5c..0000000
Binary files a/src/sndpeek/Rolloff.o and /dev/null differ
diff --git a/src/sndpeek/RtAudio.o b/src/sndpeek/RtAudio.o
deleted file mode 100644
index 0d2b552..0000000
Binary files a/src/sndpeek/RtAudio.o and /dev/null differ
diff --git a/src/sndpeek/Stk.o b/src/sndpeek/Stk.o
deleted file mode 100644
index 66eae67..0000000
Binary files a/src/sndpeek/Stk.o and /dev/null differ
diff --git a/src/sndpeek/System.o b/src/sndpeek/System.o
deleted file mode 100644
index ec4ad5c..0000000
Binary files a/src/sndpeek/System.o and /dev/null differ
diff --git a/src/sndpeek/Thread.o b/src/sndpeek/Thread.o
deleted file mode 100644
index 3a2cfcb..0000000
Binary files a/src/sndpeek/Thread.o and /dev/null differ
diff --git a/src/sndpeek/chuck_fft.o b/src/sndpeek/chuck_fft.o
deleted file mode 100644
index 435f76a..0000000
Binary files a/src/sndpeek/chuck_fft.o and /dev/null differ
diff --git a/src/sndpeek/fmatrix.o b/src/sndpeek/fmatrix.o
deleted file mode 100644
index e656ad1..0000000
Binary files a/src/sndpeek/fmatrix.o and /dev/null differ
diff --git a/src/sndpeek/fvec.o b/src/sndpeek/fvec.o
deleted file mode 100644
index 5c90bdd..0000000
Binary files a/src/sndpeek/fvec.o and /dev/null differ
diff --git a/src/sndpeek/imgui.o b/src/sndpeek/imgui.o
deleted file mode 100644
index a2f4327..0000000
Binary files a/src/sndpeek/imgui.o and /dev/null differ
diff --git a/src/sndpeek/imgui_demo.o b/src/sndpeek/imgui_demo.o
deleted file mode 100644
index 30690fc..0000000
Binary files a/src/sndpeek/imgui_demo.o and /dev/null differ
diff --git a/src/sndpeek/imgui_draw.o b/src/sndpeek/imgui_draw.o
deleted file mode 100644
index 8bb2140..0000000
Binary files a/src/sndpeek/imgui_draw.o and /dev/null differ
diff --git a/src/sndpeek/imgui_impl_sdl.o b/src/sndpeek/imgui_impl_sdl.o
deleted file mode 100644
index d17a5c3..0000000
Binary files a/src/sndpeek/imgui_impl_sdl.o and /dev/null differ
diff --git a/src/sndpeek/makefile.alsa b/src/sndpeek/makefile.alsa
index 34fb848..6d4b148 100755
--- a/src/sndpeek/makefile.alsa
+++ b/src/sndpeek/makefile.alsa
@@ -1,18 +1,41 @@
 
 CC=gcc
 CPP=g++
-INCLUDES=-I../marsyas/
+INCLUDES=-I../marsyas/ -I../imgui/
 MARSYAS_DIR=../marsyas/
+IMGUI_DIR=../imgui/
 CFLAGS=-D__LINUX_ALSA__ -D__LITTLE_ENDIAN__ $(INCLUDES) -O3 -c
-LIBS=-L/usr/X11R6/lib -lglut -lGL -lGLU -lasound -lXmu -lX11 -lXext -lXi -lm -lsndfile
+LIBS=-L/usr/X11R6/lib -lGL -lGLEW -lGLU -lglut -lasound -lXmu -lX11 -lXext -lXi -lm -lsndfile -lpthread `sdl2-config --cflags --libs`
 
 OBJS=chuck_fft.o RtAudio.o Thread.o sndpeek.o Stk.o \
 	Centroid.o DownSampler.o Flux.o LPC.o MFCC.o RMS.o Rolloff.o \
 	System.o fvec.o AutoCorrelation.o Communicator.o Hamming.o \
 	MagFFT.o NormRMS.o MarSignal.o fmatrix.o
 
-sndpeek: $(OBJS)
-	$(CPP) -o $@ $(OBJS) $(LIBS)
+OBJS2=imgui_draw.o \
+	imgui.o  \
+	imgui_demo.o \
+	imgui_impl_sdl.o \
+	imgui_impl_sdl_gl3.o
+
+
+sndpeek: $(OBJS) $(OBJS2)
+	$(CPP) -o $@ $(OBJS) $(OBJS2) $(LIBS) 
+
+imgui.o:
+	$(CC) $(CFLAGS) $(IMGUI_DIR)$*.cpp
+
+imgui_draw.o:
+	$(CC) $(CFLAGS) $(IMGUI_DIR)$*.cpp
+
+imgui_demo.o:
+	$(CC) $(CFLAGS) $(IMGUI_DIR)$*.cpp
+
+imgui_impl_sdl.o:
+	$(CC) $(CFLAGS) $(IMGUI_DIR)$*.cpp
+
+imgui_impl_sdl_gl3.o:
+	$(CC) $(CFLAGS) $(IMGUI_DIR)$*.cpp
 
 Centroid.o:
 	$(CC) $(CFLAGS) $(MARSYAS_DIR)$*.cpp
diff --git a/src/sndpeek/sndpeek b/src/sndpeek/sndpeek
deleted file mode 100755
index e0dccdc..0000000
Binary files a/src/sndpeek/sndpeek and /dev/null differ
diff --git a/src/sndpeek/sndpeek.cpp b/src/sndpeek/sndpeek.cpp
index 676b789..105bb59 100755
--- a/src/sndpeek/sndpeek.cpp
+++ b/src/sndpeek/sndpeek.cpp
@@ -60,8 +60,12 @@
 #include "RtAudio.h"
 #include "Thread.h"
 
+#if defined (__LINUX_ALSA__)
+#include <GL/glew.h>
+#endif
+
 // OpenGL
-#ifdef __APPLE__
+#if defined (__APPLE__) 
 //glew
 #include <GL/glew.h>
   #include <GLUT/glut.h>
@@ -73,6 +77,7 @@
   #include <GL/glu.h>
 #endif
 
+
 // process related
 #if defined(__OS_WINDOWS__)
   #include <process.h>
@@ -96,10 +101,8 @@
 #include "RMS.h"
 #include "Rolloff.h"
 
-//SDL
 #include <SDL2/SDL.h>
 
-
 //imgui
 #include <imgui.h>
 #include <imgui_impl_sdl.h>
@@ -593,8 +596,11 @@ int main( int argc, char ** argv )
         SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER, 1);
         SDL_GL_SetAttribute(SDL_GL_DEPTH_SIZE, 24);
         SDL_GL_SetAttribute(SDL_GL_STENCIL_SIZE, 8);
-        SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 2);
-        SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 2);
+/// ericb
+//        SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 2);
+//        SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 2);
+        SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
+        SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 3);
         SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE);
         SDL_DisplayMode current;
         SDL_GetCurrentDisplayMode(0, &current);
diff --git a/src/sndpeek/sndpeek.o b/src/sndpeek/sndpeek.o
deleted file mode 100644
index bc79a79..0000000
Binary files a/src/sndpeek/sndpeek.o and /dev/null differ
diff --git a/src/sndpeek/util_sndfile.o b/src/sndpeek/util_sndfile.o
deleted file mode 100644
index b57d023..0000000
Binary files a/src/sndpeek/util_sndfile.o and /dev/null differ`

**Comment by edselmalasig** [comment]
Yes, unfortunately it won't run under linux as i am using [(https://github.com/asantoni/libaudiodecoder] )which only works on Windows and macOS. Let me know if you want the newer version I'm working on. I will upload the new project I am planning to monetize in and delete this project.

**Comment by ebachard** [comment]
Thanks for your fast answer ! 
In fact, I'm studying imgui, not your software, and the curiosity did te rest : I checkout'ed  the sources, and did some changes to make it compile under Linux. More, I'd be happy to compile it (done) and make it work. That's the reason why I contacted you:
- the build is ok, no warning nor big problem, even linking went fine at the end
- the binary does not work (and at the end I can't see the imgui effect ;-)
More precisely: the window launches, but got frozen after some seconds. Excepted if I missed something important, I'm pretty sure I'm not far. Was the message : it should work on Linux too :-)

BTW, what's the problem with sound ? And what's the reason to not keep something working on Linux. e.g. : what about keep the current Linux code to be maintained by Linux people, the time things improve ? (and do what you want on the Windows side ? Of course, I perfectly understand you want to monetize your code, and in this case I perfectly understand the "no future" state of the current code.  So good luck for your project :-)

**Comment by ebachard** [comment]
I forgot : got the soundtrack now (was easy ;-) )

**Comment by edselmalasig** [comment]
Ok ill put the code up on GitHub probably this comming Monday. It has some bugs and a simple ui implementation. The bug is it only plays 1 song, the ui is imgui with a simple file browser.  Just to note it only works with Windows and mac. let me know if you really want it so that i could put it up to GitHub faster.

xD
